name = "steplistening"
compatibility_date = "2024-01-01"
pages_build_output_dir = "."

[[d1_databases]]
binding = "DB"
database_name = "dictation_db"
database_id = "aeb4e5bf-a460-448a-bf34-091c97c5076d"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "dictation-audio"
